apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: expo-ae-filter
spec:
  workloadSelector:
    labels:
      app: expo-echo-server
  configPatches:
  # This patch adds the wasm filter to the http connection manager listener
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.wasm
        typedConfig:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          typeUrl: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
          value:
            config:
              name: "expo_filter_name"
              root_id: "expo_filter_root_id"
              configuration: '{ "header_name": "x-wmt-expo", "header_append_value": "INJECTED_ON_PLUGIN" }'
              vm_config:
                vm_id: "my_vm_id"
                runtime: "envoy.wasm.runtime.v8"
                allow_precompiled: true
                code:
                  local:
                    filename: /var/local/lib/envoy-filters/untouched.wasm
